site_name: Seyed Mohammad Amin Sadat
theme:
  name: material
  custom_dir: docs/overrides
  favicon: material/robot
  language: en
  icon: 
    logo: material/robot
  features:
    - content.code.annotate
    - content.code.copy
    - content.tab.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.hide

  plugins:
    - typeset
    # - search
    - blog:
      blog_toc: true

  palette:
    - scheme: slate
      primary: black
      accent: deep red
      toggle:
        icon: material/weather-night
        name: switch to dark mode
    
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: switch to light mode 

# markdown_extensions:
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences
#   - attr_list
#   markdown_extensions:
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
#   - toc:
#       permalink: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - toc:
  #   permalink: false

copyright: Copyright &copy; 2024 Seyed Mohammad Amin Sadat

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

nav:
  - Home Page: index.md
  - My work:
      - 'Home': index.md
      - 'Certifications': certifications/cer.md
      - 'Publications': Publications/pub.md
      - 'Documentations': documentations/doc.md
  - Blog:
      - "Blogs": Blog/index.md
  - About me: aboutme/aboutme.md
